vagrantfile:
    target: local
    vm:
        box: puphpet/ubuntu1404-x64
        box_url: puphpet/ubuntu1404-x64
        hostname: development.lan
        memory: '512'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                vflnp_k5qnoxp4rtmu:
                    host: '8847'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: 'on'
                showgui: '0'
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            vflsf_h8uumvkgjgwt:
                target: /var/www/def-shop
                sync_type: nfs
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - htop
        - mc
        - memcached
users_groups:
    install: '1'
    groups: {  }
    users:
        - stalin
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - de_DE.UTF-8
            - en_GB.UTF-8
            - en_US.UTF-8
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_l6o06zhw8mix:
            servername: def-shop.com
            serveraliases:
                - www.def-shop.com
                - branch-redesign.def-shop.com
                - ru.def-shop.com
                - us.def-shop.com
                - de.def-shop.com
                - ua.def-shop.com
                - uk.def-shop.com
                - images.def-shop.com
                - shop.virtualnights.com
            docroot: /var/www/def-shop
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_1ipbyh6hrgp4:
                    path: /var/www/def-shop
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_oqyadq0t14cn:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - mbstring
            - curl
            - gd
            - memcached
            - memcache
            - mysqlnd
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '24575'
        session.save_path: /var/lib/php/session
        date.timezone: 'UTC'
        short_open_tag: 'On'
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_ibjlhd93q8jh:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
        xdebug.remote_cookie_expire_time: '86400'
mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: temp123
        override_options: 
            mysqld:
                innodb_file_per_table: 1
    adminer: '1'
    databases:
        mysqlnd_1vssrg2rn5ko:
            name: defshop_filter
            sql: 
        mysqlnd_1vssrg2rn5kp:
            name: products_trash
            sql: 
        mysqlnd_1vssrg2rn5kn:
            name: defshop-backend
            sql: 
        mysqlnd_1vssrg2rn5km:
            name: defshop-prod
            sql: 
